# -*- coding: utf-8 -*-
"""Colors-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMQH3km4EyQS4IttWkDVpJIuTCx7erdJ
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread('pathology_cll20x01.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize = [5, 5]), plt.axis('off')
plt.imshow(img)

azul = np.uint8([[[0,0,255]]])
hsv_azul = cv2.cvtColor(azul, cv2.COLOR_RGB2HSV)
print(hsv_azul)

def check_blue(img):
  img_hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
  lowblue = np.array([110, 250, 0])
  upblue = np.array([130, 255, 255])

  mask = cv2.inRange(img_hsv, lowblue, upblue)

  return mask

plt.imshow(check_blue(img), cmap='gray')

def change_img(mask):
  mask = cv2.GaussianBlur(mask, (3,3), 0)
  return cv2.bitwise_and(img, img, mask = mask)

plt.figure(figsize=(6,4))
res = change_img(mask)
plt.imshow(res)
plt.show()

